code/src/Xxfaxy/DryBundle/Entity/Choice.php
<?php
namespace Xxfaxy\DryBundle\Entity;

/**
 * Choice
 */
class Choice
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $dryName;

    /**
     * @var string
     */
    private $dryKey;

    /**
     * @var string
     */
    private $dryValue;

    /**
     * @var integer
     */
    private $drySort;

    /**
     * @var \DateTime
     */
    private $dryAddtime;

    /**
     * @var integer
     */
    private $dryStatus;

    /**
     * @var string
     */
    private $dryNote;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $dryChild;

    /**
     * @var \Xxfaxy\DryBundle\Entity\Choice
     */
    private $dryParent;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->dryChild = new \Doctrine\Common\Collections\ArrayCollection();
        $this->dryAddtime = new \DateTime();
    }

    public function __toString()
    {
        return ''.$this->getDryName();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set dryName
     *
     * @param string $dryName
     *
     * @return Choice
     */
    public function setDryName($dryName)
    {
        $this->dryName = $dryName;
        return $this;
    }

    /**
     * Get dryName
     *
     * @return string
     */
    public function getDryName()
    {
        return $this->dryName;
    }

    /**
     * Set dryKey
     *
     * @param string $dryKey
     *
     * @return Choice
     */
    public function setDryKey($dryKey)
    {
        $this->dryKey = $dryKey;
        return $this;
    }

    /**
     * Get dryKey
     *
     * @return string
     */
    public function getDryKey()
    {
        return $this->dryKey;
    }

    /**
     * Set dryValue
     *
     * @param string $dryValue
     *
     * @return Choice
     */
    public function setDryValue($dryValue)
    {
        $this->dryValue = $dryValue;
        return $this;
    }

    /**
     * Get dryValue
     *
     * @return string
     */
    public function getDryValue()
    {
        return $this->dryValue;
    }

    /**
     * Set drySort
     *
     * @param integer $drySort
     *
     * @return Choice
     */
    public function setDrySort($drySort)
    {
        $this->drySort = $drySort;
        return $this;
    }

    /**
     * Get drySort
     *
     * @return integer
     */
    public function getDrySort()
    {
        return $this->drySort;
    }

    /**
     * Set dryAddtime
     *
     * @param \DateTime $dryAddtime
     *
     * @return Choice
     */
    public function setDryAddtime($dryAddtime)
    {
        $this->dryAddtime = $dryAddtime;
        return $this;
    }

    /**
     * Get dryAddtime
     *
     * @return \DateTime
     */
    public function getDryAddtime()
    {
        return $this->dryAddtime;
    }

    public function getDryAddtimeString()
    {
        return $this->dryAddtime->format('Y-m-d H:i:s');
    }

    /**
     * Set dryStatus
     *
     * @param integer $dryStatus
     *
     * @return Choice
     */
    public function setDryStatus($dryStatus)
    {
        $this->dryStatus = $dryStatus;
        return $this;
    }

    /**
     * Get dryStatus
     *
     * @return integer
     */
    public function getDryStatus()
    {
        return $this->dryStatus;
    }

    /**
     * Set dryNote
     *
     * @param string $dryNote
     *
     * @return Choice
     */
    public function setDryNote($dryNote)
    {
        $this->dryNote = $dryNote;
        return $this;
    }

    /**
     * Get dryNote
     *
     * @return string
     */
    public function getDryNote()
    {
        return $this->dryNote;
    }

    /**
     * Add dryChild
     *
     * @param \Xxfaxy\DryBundle\Entity\Choice $dryChild
     *
     * @return Choice
     */
    public function addDryChild(\Xxfaxy\DryBundle\Entity\Choice $dryChild)
    {
        $this->dryChild[] = $dryChild;
        return $this;
    }

    /**
     * Remove dryChild
     *
     * @param \Xxfaxy\DryBundle\Entity\Choice $dryChild
     */
    public function removeDryChild(\Xxfaxy\DryBundle\Entity\Choice $dryChild)
    {
        $this->dryChild->removeElement($dryChild);
    }

    /**
     * Get dryChild
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getDryChild()
    {
        return $this->dryChild;
    }

    /**
     * Set dryParent
     *
     * @param \Xxfaxy\DryBundle\Entity\Choice $dryParent
     *
     * @return Choice
     */
    public function setDryParent(\Xxfaxy\DryBundle\Entity\Choice $dryParent = null)
    {
        $this->dryParent = $dryParent;
        return $this;
    }

    /**
     * Get dryParent
     *
     * @return \Xxfaxy\DryBundle\Entity\Choice
     */
    public function getDryParent()
    {
        return $this->dryParent;
    }

}

code/src/Xxfaxy/DryBundle/Form/ChoiceType.php
<?php
namespace Xxfaxy\DryBundle\Form;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChoiceType extends AbstractType
{

    public function getParent()
    {
        return 'container_aware';
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $container = $options['container'];
        $function = $container->get('service.common.function');
        $status = $function->getChoice('status');
        $builder->add('dryParent', null, array('label' => 'Choice.dryParent','label_attr'=>array('class'=>'control-label col-sm-2'),'attr'=>array('class'=>'form-control'),'query_builder'=>function($em){$qb=$em->createQueryBuilder('t');return $qb->where($qb->expr()->isNull('t.dryParent'));}));
        $builder->add('dryName',null,array('label'=>'Choice.dryName','label_attr'=>array('class'=>'control-label col-sm-2'),'attr'=>array('class'=>'form-control')));
        $builder->add('dryKey',null,array('label'=>'Choice.dryKey','label_attr'=>array('class'=>'control-label col-sm-2'),'attr'=>array('class'=>'form-control')));
        $builder->add('dryValue','textarea',array('label'=>'Choice.dryValue','label_attr'=>array('class'=>'control-label col-sm-2'),'attr'=>array('class'=>'form-control','style'=>'height:200px;')));
        $builder->add('drySort',null,array('label'=>'Choice.drySort','label_attr'=>array('class'=>'control-label col-sm-2'),'attr'=>array('class'=>'form-control')));
        $builder->add('dryStatus', 'choice',array('choices'=>$status,'multiple'=>false,'label'=>'Choice.dryStatus','label_attr'=>array('class'=>'control-label col-sm-2'),'attr'=>array('class'=>'form-control')));
        $builder->add('dryNote',null,array('label'=>'Choice.dryNote','label_attr'=>array('class'=>'control-label col-sm-2'),'attr'=>array('class'=>'form-control')));
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $this->configureOptions($resolver);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Xxfaxy\DryBundle\Entity\Choice',
            'translation_domain' => 'XxfaxyDryBundle',
        ));
    }

    public function getName()
    {
        return 'xxfaxy_drybundle_choice';
    }

}

code/src/Xxfaxy/DryBundle/Controller/ChoiceController.php
<?php
namespace Xxfaxy\DryBundle\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Xxfaxy\DryBundle\Entity\Choice;
use Xxfaxy\DryBundle\Form\ChoiceType;
use Xxfaxy\DryBundle\Form\Type\SubmitGroupForNewType;
use Xxfaxy\DryBundle\Form\Type\SubmitGroupForEditType;

class ChoiceController extends Controller
{
    public function indexAction(Request $request)
    {
        $twigData = array();
        $function = $this->get('service.common.function');
        $pagination = $this->get('service.pagination');
        $twigData['dryStatusArray'] = $function->getChoice('status');
        $em = $this->getDoctrine()->getManager();
        $qb = $em->getRepository('XxfaxyDryBundle:Choice')->createQueryBuilder('t');
        $qb = $qb->orderBy('t.drySort', 'asc');
        $total = $qb->select($qb->expr()->count('t'))->getQuery()->getSingleScalarResult();
        $pagesize = 1000;
        $page = $request->query->get('page', 1);
        $offset = ($page-1)*$pagesize;
        $result = $qb->select('t')->setFirstResult($offset)->setMaxResults($pagesize)->getQuery()->getResult();
        $pageCode = $pagination->get(array('total' => $total, 'pageSize' => $pagesize, 'language' => 'cn', 'getParameter' => $request->query->all()));
        $twigData['pageCode'] = $pageCode;
        $twigData['choices'] = $result;
        return $this->render('XxfaxyDryBundle:choice:index.html.twig', $twigData);
    }

    public function newAction(Request $request)
    {
        $function = $this->get('service.common.function');
        $choice = new Choice();
        $form = $this->createForm('Xxfaxy\DryBundle\Form\ChoiceType', $choice);
        $form->add('SubmitGroup', SubmitGroupForNewType::class, array('label' => ' ', 'label_attr' => array('class' => 'control-label col-sm-2'), 'attr' => array('class' => 'form-control'), 'mapped' => false));
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($choice);
            $em->flush();
            $this->addFlash('message_success', $function->translation('operationSuccess'));
            $post = $function->getFormData($request->request->all());
            $SubmitGroup = $post['SubmitGroup'];
            if(isset($SubmitGroup['submit'])){
                return $this->redirectToRoute('choice_new');
            }
            else if(isset($SubmitGroup['submitAndShow'])){
                return $this->redirectToRoute('choice_show', array('id' => $choice->getId()));
            }
            else if(isset($SubmitGroup['submitAndList'])){
                return $this->redirectToRoute('choice_index');
            }
            else if(isset($SubmitGroup['submitAndEdit'])){
                return $this->redirectToRoute('choice_edit', array('id' => $choice->getId()));
            }
        }
        return $this->render('XxfaxyDryBundle:choice:new.html.twig', array(
            'choice' => $choice,
            'form' => $form->createView(),
        ));
    }

    public function showAction(Choice $choice)
    {
        $twigData = array();
        $function = $this->get('service.common.function');
        $twigData['dryStatusArray'] = $function->getChoice('status');
        $twigData['choice'] = $choice;
        return $this->render('XxfaxyDryBundle:choice:show.html.twig', $twigData);
    }

    public function editAction(Request $request, Choice $choice)
    {
        $function = $this->get('service.common.function');
        $editForm = $this->createForm('Xxfaxy\DryBundle\Form\ChoiceType', $choice);
        $editForm->add('SubmitGroup', SubmitGroupForEditType::class, array('label' => ' ', 'label_attr' => array('class' => 'control-label col-sm-2'), 'attr' => array('class' => 'form-control'), 'mapped' => false));
        $editForm->handleRequest($request);
        if($editForm->isSubmitted() && $editForm->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->persist($choice);
            $em->flush();
            $this->addFlash('message_success', $function->translation('operationSuccess'));
            $post = $function->getFormData($request->request->all());
            $SubmitGroup = $post['SubmitGroup'];
            if(isset($SubmitGroup['submit'])){
                return $this->redirectToRoute('choice_edit', array('id' => $choice->getId()));
            }
            else if(isset($SubmitGroup['submitAndShow'])){
                return $this->redirectToRoute('choice_show', array('id' => $choice->getId()));
            }
            else if(isset($SubmitGroup['submitAndList'])){
                return $this->redirectToRoute('choice_index');
            }
            else if(isset($SubmitGroup['submitAndNew'])){
                return $this->redirectToRoute('choice_new');
            }
        }
        return $this->render('XxfaxyDryBundle:choice:edit.html.twig', array(
            'choice' => $choice,
            'edit_form' => $editForm->createView(),
        ));
    }

    public function deleteAction(Request $request, Choice $choice)
    {
        $form = $this->createDeleteForm($choice);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $em = $this->getDoctrine()->getManager();
            $em->remove($choice);
            $em->flush();
        }
        return $this->redirectToRoute('choice_index');
    }

    private function createDeleteForm(Choice $choice)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('choice_delete', array('id' => $choice->getId())))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }

}

code/src/Xxfaxy/DryBundle/Resources/views/choice/edit.html.twig
{% extends 'base.html.twig' %}
{% block body_bar %}
    <h5>{{ dry_translation('edit') }}</h5>
    <div class="ibox-tools">
        <a class="btn btn-outline btn-info" href="{{ path("choice_new") }}" data-route="choice_new">{{ dry_translation('new') }}</a>
        <a class="btn btn-outline btn-info" href="{{ path("choice_index") }}" data-route="choice_index">{{ dry_translation('list') }}</a>
    </div>
{% endblock %}
{% block body %}
    {{ form_start(edit_form,{attr:{"class":"form-horizontal"}}) }}
        {{ form_widget(edit_form) }}
    {{ form_end(edit_form) }}
{% endblock %}

code/src/Xxfaxy/DryBundle/Resources/views/choice/index.html.twig
{% extends 'base.html.twig' %}
{% block body_bar %}
    <h5>{{ dry_translation('list') }}</h5>
    <div class="ibox-tools">
        <a class="btn btn-outline btn-info" href="{{ path("choice_new") }}" data-route="choice_new">{{ dry_translation('new') }}</a>
    </div>
{% endblock %}
{% block body %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>{{ dry_translation('Choice.id') }}</th>
                <th>{{ dry_translation('Choice.dryParent') }}</th>
                <th>{{ dry_translation('Choice.dryName') }}</th>
                <th>{{ dry_translation('Choice.dryKey') }}</th>
                <th>{{ dry_translation('Choice.dryValue') }}</th>
                <th>{{ dry_translation('Choice.drySort') }}</th>
                <th>{{ dry_translation('Choice.dryAddtime') }}</th>
                <th>{{ dry_translation('Choice.dryStatus') }}</th>
                <th>{{ dry_translation('Choice.dryNote') }}</th>
                <th>{{ dry_translation('action') }}</th>
            </tr>
        </thead>
        <tbody>
            {% for choice in choices %}
            <tr>
                <td>{{ choice.id }}</td>
                <td>{{ choice.dryParent }}</td>
                <td>{{ choice.dryName }}</td>
                <td>{{ choice.dryKey }}</td>
                <td>{{ call_method('detailShow', choice.dryValue)|raw }}</td>
                <td>{{ choice.drySort }}</td>
                <td>{{ choice.dryAddtimeString }}</td>
                <td>{{ call_method('statusShow', dryStatusArray, choice.dryStatus)|raw }}</td>
                <td>{{ choice.dryNote }}</td>
                <td>
                    <div class="btn-group">
                        <a class="btn btn-primary" href="{{ dry_path('choice_show', choice.id) }}" data-route="choice_show">{{ dry_translation('show') }}</a>
                        <a class="btn btn-primary" href="{{ dry_path('choice_edit', choice.id) }}" data-route="choice_edit">{{ dry_translation('edit') }}</a>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

code/src/Xxfaxy/DryBundle/Resources/views/choice/new.html.twig
{% extends 'base.html.twig' %}
{% block body_bar %}
    <h5>{{ dry_translation('new') }}</h5>
    <div class="ibox-tools">
        <a class="btn btn-outline btn-info" href="{{ path("choice_index") }}" data-route="choice_index">{{ dry_translation('list') }}</a>
    </div>
{% endblock %}
{% block body %}
    {{ form(form,{attr:{"class":"form-horizontal"}}) }}
{% endblock %}

code/src/Xxfaxy/DryBundle/Resources/views/choice/show.html.twig
{% extends 'base.html.twig' %}
{% block body_bar %}
    <h5>{{ dry_translation('show') }}</h5>
    <div class="ibox-tools">
        <a class="btn btn-outline btn-info" href="{{ dry_path("choice_new") }}" data-route="choice_new">{{ dry_translation('new') }}</a>
        <a class="btn btn-outline btn-info" href="{{ dry_path("choice_edit", choice.id) }}" data-route="choice_edit">{{ dry_translation('edit') }}</a>
        <a class="btn btn-outline btn-info" href="{{ dry_path("choice_index") }}" data-route="choice_index">{{ dry_translation('list') }}</a>
    </div>
{% endblock %}
{% block body %}
    <table class="table">
        <tbody>
            <tr>
                <th style="border-top:none;">{{ dry_translation('Choice.id') }}</th>
                <td style="border-top:none;">{{ choice.id }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.dryParent') }}</th>
                <td>{{ choice.dryParent }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.dryName') }}</th>
                <td>{{ choice.dryName }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.dryKey') }}</th>
                <td>{{ choice.dryKey }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.dryValue') }}</th>
                <td>{{ choice.dryValue|nl2br }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.drySort') }}</th>
                <td>{{ choice.drySort }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.dryAddtime') }}</th>
                <td>{{ choice.dryAddtimeString }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.dryStatus') }}</th>
                <td>{{ dryStatusArray[choice.dryStatus] }}</td>
            </tr>
            <tr>
                <th>{{ dry_translation('Choice.dryNote') }}</th>
                <td>{{ choice.dryNote }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}